remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: [Portfolio: Roy ]
description: [an aspiring Data Analyst currently pursuing an MBA focused on Business and Data Analytics and this is my portfolio ] 